name: oauth_webauth
description: This plugin provides an alternative to AppAuth using WebView for OAuth 2.0 authorization/authentication.
version: 4.0.1+1
repository: https://github.com/luis901101/oauth_webauth
issue_tracker: https://github.com/luis901101/oauth_webauth/issues


environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter
  oauth2: ^2.0.0
  flutter_inappwebview: ^5.4.0+2
  shared_preferences: ^2.0.0
  http: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter: