name: oauth_webauth
description: This plugin provides an alternative to AppAuth using WebView for OAuth 2.0 authorization/authentication.
version: 5.2.0
repository: https://github.com/luis901101/oauth_webauth
issue_tracker: https://github.com/luis901101/oauth_webauth/issues
topics:
  - oauth
  - oauth2
  - login
  - social-login


environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: '>=3.3.0'

dependencies:
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter
  oauth2: ^2.0.0
  flutter_inappwebview: ^6.0.0
  shared_preferences: ^2.0.0
  web: ^1.1.1
  http: '>=0.13.0 <2.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter: