name: oauth_webauth
description: This plugin provides an alternative to AppAuth using WebView for OAuth 2.0 authorization/authentication.
version: 1.0.0+2
homepage: https://github.com/luis901101/oauth_webauth

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter
  oauth2: ^2.0.0
  webviewx: ^0.2.1
  flutter_inappwebview: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter: